### ISSUE TITLE
stucked at "running" when run binance_page.py

### ISSUE THREAD

**Issue by defidummy** [manuelhb14/exchangesListingsBot#1]
i tried to run binance_page.py but it seems to only stucked at "running" 

Do you have a telegram/discord? Would love to chat -anh

**Comment by manuelhb14** [comment]
binance_page was created to see if listing news were added there before announcing them in Twitter which was not the case. exchanges_bot.py is the main file, will be adding more exchanges this week.  If you have any doubt you can DM me on Telegram @manuelhb14.
